In [30]:
import cv2
import torch
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.datasets as datasets
import torchvision.models as models
import torchvision.transforms as transforms
from torch.utils.data import Dataset
import numpy as np
import PIL.Image
import os

In [31]:
filename = '/Users/kevywilly/projects/felix-ai/data/training/tags/blocked/1707973276-3814282.jpg'

In [32]:
color_jitter = transforms.ColorJitter(0.1, 0.1, 0.1, 0.1)

In [40]:
def show(image):
    cv2.imshow('myimage',image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [42]:
image = PIL.Image.open(filename)
i2 = cv2.imread(filename)
show(i2)

In [ ]:
i2 = cv2.flip(i2,1)
show(i2)

In [39]:



print(i2.shape)
image = color_jitter(image)
image = transforms.functional.resize(image, (224, 224))
image = transforms.functional.to_tensor(image)
print(4,image.shape)
image = image.numpy()[::-1].copy()
print(5,image.shape)
image = torch.from_numpy(image)
print(6,image.shape)
image = transforms.functional.normalize(image, [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])



(1232, 1640, 3)
4 torch.Size([3, 224, 224])
5 (3, 224, 224)
6 torch.Size([3, 224, 224])


In [26]:
t1 = load_using_cv2()

In [27]:
t1.shape

torch.Size([3, 224, 224])

In [28]:
t1[None,...].shape

torch.Size([1, 3, 224, 224])

In [27]:
print(a.transpose((2,0,1)))


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [29]:
print(a[None, ...])

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [16]:
image.shape

torch.Size([3, 224, 224])

In [17]:
image[None,...].shape

torch.Size([1, 3, 224, 224])

In [18]:
filename

'/Users/kevywilly/projects/felix-ai/data/training/tags/blocked/1707973276-3814282.jpg'